### PR TITLE
Deploy site via Netlify

### LINKED ISSUE #8: Switch to Netlify for CI and Deployments
For Hugo websites, Travis and GitHub Pages do not provide great solutions. Deployments require a hacky deploy script (#5)- Travis CI's `pages` deployer doesn't work if the deployment directory is a submodule (see the results of #6). Furthermore, developers need to pull down the PR branch to preview content.

[Netlify](https://www.netlify.com/) provides a platform built for website CI/CD. This is what upstream Kubernetes uses for its docs website, and open source projects are eligible for free services. It's best feature is perhaps the preview deployments - reviewers can review the resulting content of a website without pulling down code.

### PR DESCRIPTION
**Pull request by adambkaplan**
- Add status badge to README
- Add netlify logo to footer
- Add netlify.toml for PR preview deployments

Fixes #8

### CODE REVIEW

**Comment by adambkaplan** [comment]
Netlify has been configured correctly for this repo. You can see in the status checks the `deploy-preview` which shows a preview of the live site.

**Review by zhangtbj — APPROVED** [review]

**Comment by zhangtbj** [comment]
Hi @adambkaplan ,

I have approved this PR but I am not the authorized user to do the action in the repo.

Please help add me so that I can modify or merge PR here.
Thanks!

**Comment by adambkaplan** [comment]
@zhangtbj Prow merges code automatically if the pull request has the right set of labels. Our repo is configured to require the "approved" and "lgtm" labels. Approved can only be added by approvers in the OWNERS file, lgtm can be added by anyone in the Shipwright organization.

**Pull request merged**
