### PR TITLE
Website updates for v0.10.0

### PR DESCRIPTION
**Pull request by SaschaSchwarze0**
Release notes and blog post for v0.10.0.

### CODE REVIEW

**Review by qu1queee — APPROVED** [review]
thank you

Per the content length, we can mention that we bumped to Tekton v0.35.* in the "Smaller Items" section

/lgtm

**Comment by SaschaSchwarze0** [comment]
> Per the content length, we can mention that we bumped to Tekton v0.35.* in the "Smaller Items" section

Done

**Comment by SaschaSchwarze0** [comment]
/hold

Should be merged not before we have an operator release and published the artifacts.

**Review by adambkaplan — APPROVED** [review]
/approve

Will add LGTM once the operator is on the community operators repo.

**Pull request merged**
