### PR TITLE
content: Fix broken link to build controller deployment YAML manifest

### PR DESCRIPTION
**Pull request by timflannagan**
Update the configuration.md documentation and fix the broken link to the
build controller deployment YAML manifest.

### CODE REVIEW

**Comment by timflannagan** [comment]
Found another one going through the docs :laughing: 

I pointed the link to the latest tag vs. the main branch to help cut down on broken links in the future.

**Comment by timflannagan** [comment]
Might be worth adding a CI check that lints PRs (e.g. https://github.com/operator-framework/olm-docs/blob/master/hack/ci/link-check.sh). I can open an issue tracking that if you're interested.

**Comment by SaschaSchwarze0** [comment]
Hi @timflannagan, sry for having missed this. I am not sure if we here want to point to the latest version or main. Kind of related to the doc synchronization where Adam has looked in.

/assign adambkaplan

**Comment by timflannagan** [comment]
Trying to clear my open PRs so I'm going to close this out as it's been sitting for a while and open an issue instead: https://github.com/shipwright-io/website/issues/52.

**Pull request closed without merging**
