### PR TITLE
Set up Travis CI

### PR DESCRIPTION
**Pull request by adambkaplan**
- Add node_modules/ to .gitignore
- Add travis config
- Add Makefile with build and travis targets
- Add script to install Hugo at our given version
- Set up npm - Docsy needs postcss to compile the Hugo site

### CODE REVIEW

**Comment by adambkaplan** [comment]
@sbose78 @qu1queee this may need to be merged before Travis CI does anything for us.

**Review by sbose78 — APPROVED** [review]

**Comment by sbose78** [comment]
Go ahead and merge it whenever you ready, @adambkaplan

**Comment by adambkaplan** [comment]
Going to "green button" merge this.

**Pull request merged**
