### PR TITLE
Add Favicons

### PR DESCRIPTION
**Pull request by adambkaplan**
- Generated favicons from square logo
- Add icon sizes for mobile web
- Add Edge icon browser config XML
- Override favicon.html partial from Docsy theme.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/approve

Self approval

**Comment by sftim** [comment]
Not sure if I can, but:
/lgtm

**Comment by adambkaplan** [comment]
odd... GitHub shows the favicons as "empty files", but the Netlify preview includes the favicon just fine.

**Review by SaschaSchwarze0 — APPROVED** [review]

**Pull request merged**
