### PR TITLE
Automatic deployments to Github Pages

### PR DESCRIPTION
**Pull request by adambkaplan**
- Remove .gitignore for public/
- Add org-wide GitHub Pages repo as a submodule in pubic/
- Add deploy script and Makefile target
- Update travis to deploy on merge

### CODE REVIEW

**Review by coreydaley-redhat — APPROVED** [review]

**Comment by adambkaplan** [comment]
/hold

This may actually trigger an infinite Travis build loop.

1. Deploy script bumps the submodule in /public.
2. Submodule commit requires a bump in the commit sha in .gitmodules
3. New commit means new build, with new content in `/public`

**Pull request closed without merging**
