### PR TITLE
CDF Incubating Project

### PR DESCRIPTION
**Pull request by adambkaplan**
- Add CD Foundation logo to footer
- Add footer text indicating Shipwright is an incubating project
- Blog post: Announce we are a CDF Incubating Project
- Blog post: Add links to talks from cdCon 2021:
  - Jason Hall - Intro to Shipwright
  - Adam Kaplan and Enrique Encalada - Project Shipwright In Depth

### CODE REVIEW

**Comment by adambkaplan** [comment]
/approve

Self-approving

**Comment by adambkaplan** [comment]
/hold

Need to add the link to the press release

**Review by SaschaSchwarze0 — COMMENTED** [review]
/lgtm

**Pull request merged**
