### PR TITLE
Release v0.3.0

### PR DESCRIPTION
**Pull request by adambkaplan**
- Update main page with link to the latest release
- Add post with link to release notes

### CODE REVIEW

**Review by qu1queee — APPROVED** [review]
thanks @adambkaplan . Lgtm. Side topic, can you check if the new tag is available at https://quay.io/repository/shipwright/shipwright-operator?tab=tags ?

**Comment by adambkaplan** [comment]
/hold

Yeah, don't see the new tag yet. May need to look in Travis to see what happened.

**Comment by adambkaplan** [comment]
/hold cancel

The new tag is now up, was able to rebuild on Travis.

**Comment by adambkaplan** [comment]
/approve

Self-approving per Enrique's comment above.

**Review by qu1queee — APPROVED** [review]

**Pull request merged**
