### PR TITLE
Build v0.2.0 Release

### PR DESCRIPTION
**Pull request by adambkaplan**
- Adding release announcement for v0.2.0.
- Updating previous releases to refer to "Build" component

### CODE REVIEW

**Comment by adambkaplan** [comment]
/hold

Need to wait for the tag to be published before we publish

**Comment by zhangtbj** [comment]
The new `v0.2.0` release and tag is ready:
https://github.com/shipwright-io/build/releases/tag/v0.2.0

We can go ahead.

**Review by zhangtbj — APPROVED** [review]

**Review by adambkaplan — COMMENTED** [review]
/approve

**Pull request merged**
