### PR TITLE
Add v0.12.0 installation post

### PR DESCRIPTION
**Pull request by qu1queee**
# Changes

Provide installation steps for v0.12.0

# Submitter Checklist

- [ ] Includes tests if functionality changed/was added
- [ ] Includes docs if changes are user-facing
- [x] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)
- [x] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/main/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by rolfedh — COMMENTED** [review]
Nice work, @qu1queee! I've offered a few suggestions. HTH.

**Review by rolfedh — APPROVED** [review]
LGTM

**Review by adambkaplan — COMMENTED** [review]
/approve

Looks good to me! Does it make sense to take our releases out of the "draft" state?

**Review by SaschaSchwarze0 — APPROVED** [review]
/lgtm

**Pull request merged**
