### PR TITLE
Add asciidoctor to website.

### PR DESCRIPTION
**Pull request by adambkaplan**
- Bump website dependencies (hugo, npm)
- Add Asciidoctor to website.
- Update deployment definition for Netlify.

Part of #75

### CODE REVIEW

**Comment by adambkaplan** [comment]
cc @rolfedh

**Comment by rolfedh** [comment]
Yes. As I understand it, with this enhancement, with can use markdown and asciidoc content. 
I would avoid having duplicate content in both file types. For example, with `build.adoc` and `build.md`, contributors might not know which file to modify.

**Comment by rolfedh** [comment]
In my tests, if you have two content files such as `build.adoc` and `build.md`, the markdown file "wins."

**Comment by rolfedh** [comment]
In my tests, if you have two content files such as `build.adoc` and `build.md`, the markdown file "wins."

**Pull request merged**
